name: Asset Management
favicon: null
layout_spectrum: 0.76821
typography_spectrum: 0.74804
title: Simon-Pierre Jarry - Gestionnaire de portefeuille chez 3Macs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00578e'
    - '#25709e'
    - '#659aba'
    - '#a6c5d7'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
