name: AssetManagement
favicon: null
layout_spectrum: 0.10261415736749768
typography_spectrum: 0.9827332287095487
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4000001042149961
  lightness: 0.3624774250201881
  saturation: 0.5721551473252475
  rhythmicContrast: 0.8802463987376541
purpose: []
