name: AssetManagement
favicon: null
layout_spectrum: 0.93562
typography_spectrum: 0.50722
title: Simon-Pierre Jarry - Gestionnaire de portefeuille chez 3Macs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00578e'
    - '#25709e'
    - '#659aba'
    - '#a6c5d7'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
